version: '3.7'
services:
  pokedex:
    build: ./pokedex
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
  
  nginx:
    build: ./nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    networks:
    - my-network

networks:
  my-network:
