version: '3.5'
services:
  backend:
    build: ./backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
  letters:
    build: ./letters
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
  numbers:
    build: ./numbers
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
  frontend:
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
  nginx:
    build: ./nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
  databass:
    build: ./db
    ports:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: XD12370
      MYSQL_USER: madmin
      MYSQL_PASSWORD: adminpass
    networks:
    - my-network
    container_name: databass

    
networks:
  my-network:
