version: '3.5'
services:
  backend:
    image: docktermo/backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
    - SECRET_KEY=${SECRET_KEY}
    deploy:
      replicas: 2
    networks:
    - my-network
  letters:
    image: docktermo/letters:${VERSION}
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    environment:
    - SECRET_KEY=${SECRET_KEY}
    deploy:
      replicas: 2
    networks:
    - my-network
  numbers:
    image: docktermo/numbers:${VERSION}
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    environment:
    - SECRET_KEY=${SECRET_KEY}
    deploy:
      replicas: 2
    networks:
    - my-network
  frontend:
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
    - SECRET_KEY=${SECRET_KEY}
    deploy:
      replicas: 2
    networks:
    - my-network
  databass:
    image: docktermo/databass
    ports:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    networks:
    - my-network
    container_name: databass

    
networks:
  my-network:
