- hosts: swarm
  become: true
  roles: 
  - Docker

- hosts: jenkins
  become: true
  roles:
  - Jenkins

- hosts: NGINX
  become: true 
  roles: 
  - NGINX

- hosts: swarmmanger
  become: true
  tasks:
  - name: Initialize swarm
    shell: docker swarm init
    rune_once: true
    tags: swarm
  - name: Get join token
    shell: docker swarm join-token --quiet worker
    register: worker_token
    tags: swarm

- hosts: swarmworker
  become: true
  tasks:
  - name: join the docker swarm
    shell: "docker swarm join --token {{ hostvars['51.105.36.162']['worker_token']['stdout'] }} {{ hostvars['51.105.36.162']['ansible_default_ipv4']['address'] }}:2377"
    tags: swarm

